baseURL      = "https://nartudy.github.io"
baseurl      = "https://nartudy.github.io"
title        = "Hung's Blog"
languageCode = "en-us"
theme        = "hello-friend"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Enable toggle theme
  enableThemeToggle = true

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]


  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # Uncomment this if you want a portrait on your start page
  #
  # [params.portrait]
  #   path     = "/img/image.jpg"
  #   alt      = "Portrait"
  #   maxWidth = "50px"

  # Social icons
  [[params.social]]
    name = "facebook"
    url  = "https://facebook.com/hungtran.19197"

  [[params.social]]
    name = "email"
    url  = "mailto:hungtranduy.dev@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/hungtran97"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "My Blog"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
